### ISSUE TITLE
update teach parser

### ISSUE THREAD

**Issue by machow** [datacamp/docwhat#1]
see https://github.com/datacamp/teach-parser/issues/5

branch for implementing updates here: https://github.com/datacamp/docwhat/tree/test-md

It looks like the only piece left is converting the md->html on docwhat's end now

**Comment by filipsch** [comment]
Closing this, as docwhat is not actively pursued anymore. We resorted to in-package docs, where soon we will also explain in more detail how SCT authors can experiment locally with SCT code.
